Fix: ExampleVideo.tsx style error
The error `src/components/ExampleVideo.tsx(80,14): error TS2322: Type '{ children: string; jsx: true; }' is not assignable to type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'. Property 'jsx' does not exist on type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'` indicates an issue with how the `style jsx` is being used. This commit removes the incorrect `jsx: true` property from the style tag.